### ISSUE TITLE
执行报错 name 'request_in_progress' is not defined

### ISSUE THREAD

**Issue by bxjxxyy** [CelestialRipple/Midjourney-Web-API#4]
在启动服务后，调用send_and_receive的时候会报错
![image](https://github.com/CelestialRipple/Midjourney-Web-API/assets/26214176/b63b212f-916e-4735-a4de-7f99230117cc)
没看懂是什么情况，声明了全局变量，启动的main函数里面也有声明赋值，为什么调用的时候会not defined

**Comment by CelestialRipple** [comment]
没能复现这个bug，可能是你运行环境的问题

**Comment by bxjxxyy** [comment]
会不会是因为我python版本是3.10的原因？你那python版本是多少？

**Comment by bxjxxyy** [comment]
好像是我pycharm的版本问题，用cmd进入虚拟环境运行就不会报这个错误了。
我改用vscode调试，上面的问题没有了。但是在执行到这里的时候post请求400了
![image](https://github.com/CelestialRipple/Midjourney-Web-API/assets/26214176/a2c47412-08c7-4d17-b861-766ea88e6f2c)

**Comment by CelestialRipple** [comment]
这应该是json配置错了

**Comment by bxjxxyy** [comment]
果然，切换账号的时候有信心给漏了没替换过来   现在成功了
