### ISSUE TITLE
高手，请问怎么参数怎样填写呢？哪些是必填？

### ISSUE THREAD

**Issue by panjiping** [CelestialRipple/Midjourney-Web-API#5]
{"channelid": [ "xxxx" , "xxx", "xxxx"], "authorization": "", "application_id": "", "guild_id": "", "session_id": "", "version": "", "id": "", "flags":[ "--v 5", "--niji 5"]}

**Comment by CelestialRipple** [comment]
请仔细阅读readme
<img width="1083" alt="截屏2023-06-24 10 11 15" src="https://github.com/CelestialRipple/Midjourney-Web-API/assets/115361435/2fe985a0-8158-4345-8d0c-3d2f90b722f6">

**Comment by panjiping** [comment]
已经Ok, 谢谢
