### ISSUE TITLE
Failed to process your command :c

### ISSUE THREAD

**Issue by Junaid-Bashir** [CelestialRipple/Midjourney-Web-API#6]
after every 2nd image generation request i am seeing (Failed to process your command :c) on discord.
any recommended change in the code??

**Comment by CelestialRipple** [comment]
Please provide screenshots of Discord and  error logs

**Comment by Junaid-Bashir** [comment]
**Discord Screenshot**
[https://trovalost.it/wp-content/uploads/2023/08/Screenshot-2023-08-15-alle-13.45.44.png](url)

**error logs**
Code is not giving any error, When above screenshot issue occur, Its just running forever untill i stop the running code and run again

**Comment by CelestialRipple** [comment]
Type /settings in discord and take a screenshot

**Comment by CelestialRipple** [comment]
Can the first image be generated normally?

**Comment by Junaid-Bashir** [comment]
I think it was midjourney server issue 
now its working fine Thanks for your support
